CREATE TABLE MARCA(
cod_marca INTEGER PRIMARY KEY,
nom_marca VARCHAR(100) NOT NULL,
UNIQUE (nom_marca)

);
CREATE TABLE MODELO(
cod_modelo INTEGER PRIMARY KEY, 
des_modelo VARCHAR(100) NOT NULL,
cod_marca INT NOT NULL,
FOREIGN KEY (cod_marca) REFERENCES MARCA (cod_marca) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE VEICULO(
cod_veiculo INTEGER PRIMARY KEY, 
des_placa VARCHAR(10) NOT NULL,
cod_modelo INT NOT NULL,
FOREIGN KEY (cod_modelo) REFERENCES MODELO (cod_modelo),
UNIQUE( des_placa, cod_modelo)
)
